// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoBmtYvSq9BF3zd5xQDr-YxXITbuzhmr4',
    appId: '1:530663432007:web:fae5cbacd916ae6e73b662',
    messagingSenderId: '530663432007',
    projectId: 'chat-app-d0be1',
    authDomain: 'chat-app-d0be1.firebaseapp.com',
    storageBucket: 'chat-app-d0be1.appspot.com',
    measurementId: 'G-XM8ELTZDM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1tJhC8Wn1oqYWQpo7jDTJiUE3g9Vj-A8',
    appId: '1:530663432007:android:b623e7c6ff27a1bc73b662',
    messagingSenderId: '530663432007',
    projectId: 'chat-app-d0be1',
    storageBucket: 'chat-app-d0be1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2-yYIFE5WGhFf6xWWd4RS1K7mQXGGGdo',
    appId: '1:530663432007:ios:f63d922a3a36af2673b662',
    messagingSenderId: '530663432007',
    projectId: 'chat-app-d0be1',
    storageBucket: 'chat-app-d0be1.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2-yYIFE5WGhFf6xWWd4RS1K7mQXGGGdo',
    appId: '1:530663432007:ios:3f713a419d259beb73b662',
    messagingSenderId: '530663432007',
    projectId: 'chat-app-d0be1',
    storageBucket: 'chat-app-d0be1.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
